import Head from 'next/head'
import Image from 'next/image'
import SideBar from "../components/SideBar";

export default function Home() {
  return (
    <div className='container mx-auto'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <h1 className='text-3xl bg-red-700'>Good Days Cafe</h1>
        <div className='flex flex-row'>
          <div className=''>
            <SideBar />
          </div>
          <div className=''>
          </div>
        </div>
      </main>

      <footer className=''>
      </footer>
    </div>
  )
}
