import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='w-screen'>
        <img className='w-full h-52 object-cover' src='banner.jpg'></img>
        <img className='rounded-full absolute w-32' src='profile.png'></img>
      </div>
      <main className="container mx-auto py-6">
        <h1 className="text-3xl font-extrabold">
          Good Day Vending
        </h1>
      </main>

      <footer className="">
      </footer>
    </div>
  )
}
